//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EmployeeManagement.Models;

    public partial class employeeDBEntities : DbContext
    {
        public employeeDBEntities() : base("name=employeeDBEntities") { }

        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Map the Employee entity to the correct table name
            modelBuilder.Entity<Employee>().ToTable("employee");

            base.OnModelCreating(modelBuilder);
        }
    }
}